// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ldot
arma::colvec ldot(arma::colvec tau, double alpha, double lambda, arma::mat D, double a, double b);
RcppExport SEXP _SpatGEVBMA_ldot(SEXP tauSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP DSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(ldot(tau, alpha, lambda, D, a, b));
    return rcpp_result_gen;
END_RCPP
}
// j_double_prime_new
double j_double_prime_new(double tau, double tau_hat, double varsigma, double kappa, double xi_hat, arma::colvec eps);
RcppExport SEXP _SpatGEVBMA_j_double_prime_new(SEXP tauSEXP, SEXP tau_hatSEXP, SEXP varsigmaSEXP, SEXP kappaSEXP, SEXP xi_hatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_hat(tau_hatSEXP);
    Rcpp::traits::input_parameter< double >::type varsigma(varsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type xi_hat(xi_hatSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(j_double_prime_new(tau, tau_hat, varsigma, kappa, xi_hat, eps));
    return rcpp_result_gen;
END_RCPP
}
// j_prime_new
double j_prime_new(double tau, double tau_hat, double varsigma, double kappa, double xi_hat, arma::colvec eps);
RcppExport SEXP _SpatGEVBMA_j_prime_new(SEXP tauSEXP, SEXP tau_hatSEXP, SEXP varsigmaSEXP, SEXP kappaSEXP, SEXP xi_hatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_hat(tau_hatSEXP);
    Rcpp::traits::input_parameter< double >::type varsigma(varsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type xi_hat(xi_hatSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(j_prime_new(tau, tau_hat, varsigma, kappa, xi_hat, eps));
    return rcpp_result_gen;
END_RCPP
}
// gev_like_new
arma::colvec gev_like_new(arma::colvec Y, double mu, double kappa, double xi);
RcppExport SEXP _SpatGEVBMA_gev_like_new(SEXP YSEXP, SEXP muSEXP, SEXP kappaSEXP, SEXP xiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    rcpp_result_gen = Rcpp::wrap(gev_like_new(Y, mu, kappa, xi));
    return rcpp_result_gen;
END_RCPP
}
// g_prime_new
double g_prime_new(double tau, double tau_hat, double varsigma, double xi, double kappa_hat, arma::colvec eps);
RcppExport SEXP _SpatGEVBMA_g_prime_new(SEXP tauSEXP, SEXP tau_hatSEXP, SEXP varsigmaSEXP, SEXP xiSEXP, SEXP kappa_hatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_hat(tau_hatSEXP);
    Rcpp::traits::input_parameter< double >::type varsigma(varsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_hat(kappa_hatSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(g_prime_new(tau, tau_hat, varsigma, xi, kappa_hat, eps));
    return rcpp_result_gen;
END_RCPP
}
// g_double_prime_new
double g_double_prime_new(double tau, double tau_hat, double varsigma, double xi, double kappa_hat, arma::colvec eps);
RcppExport SEXP _SpatGEVBMA_g_double_prime_new(SEXP tauSEXP, SEXP tau_hatSEXP, SEXP varsigmaSEXP, SEXP xiSEXP, SEXP kappa_hatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_hat(tau_hatSEXP);
    Rcpp::traits::input_parameter< double >::type varsigma(varsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_hat(kappa_hatSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(g_double_prime_new(tau, tau_hat, varsigma, xi, kappa_hat, eps));
    return rcpp_result_gen;
END_RCPP
}
// f_prime_new
double f_prime_new(double tau, double tau_hat, double varsigma, double xi, double kappa, arma::colvec R);
RcppExport SEXP _SpatGEVBMA_f_prime_new(SEXP tauSEXP, SEXP tau_hatSEXP, SEXP varsigmaSEXP, SEXP xiSEXP, SEXP kappaSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_hat(tau_hatSEXP);
    Rcpp::traits::input_parameter< double >::type varsigma(varsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(f_prime_new(tau, tau_hat, varsigma, xi, kappa, R));
    return rcpp_result_gen;
END_RCPP
}
// f_double_prime_new
double f_double_prime_new(double tau, double tau_hat, double varsigma, double xi, double kappa, arma::colvec R);
RcppExport SEXP _SpatGEVBMA_f_double_prime_new(SEXP tauSEXP, SEXP tau_hatSEXP, SEXP varsigmaSEXP, SEXP xiSEXP, SEXP kappaSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_hat(tau_hatSEXP);
    Rcpp::traits::input_parameter< double >::type varsigma(varsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(f_double_prime_new(tau, tau_hat, varsigma, xi, kappa, R));
    return rcpp_result_gen;
END_RCPP
}
// g_eta_prime_new
double g_eta_prime_new(double tau, double tau_hat, double varsigma, double xi, double eta_hat, arma::colvec eps);
RcppExport SEXP _SpatGEVBMA_g_eta_prime_new(SEXP tauSEXP, SEXP tau_hatSEXP, SEXP varsigmaSEXP, SEXP xiSEXP, SEXP eta_hatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_hat(tau_hatSEXP);
    Rcpp::traits::input_parameter< double >::type varsigma(varsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type eta_hat(eta_hatSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(g_eta_prime_new(tau, tau_hat, varsigma, xi, eta_hat, eps));
    return rcpp_result_gen;
END_RCPP
}
// g_eta_double_prime_new
double g_eta_double_prime_new(double tau, double tau_hat, double varsigma, double xi, double eta_hat, arma::colvec eps);
RcppExport SEXP _SpatGEVBMA_g_eta_double_prime_new(SEXP tauSEXP, SEXP tau_hatSEXP, SEXP varsigmaSEXP, SEXP xiSEXP, SEXP eta_hatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_hat(tau_hatSEXP);
    Rcpp::traits::input_parameter< double >::type varsigma(varsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type eta_hat(eta_hatSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(g_eta_double_prime_new(tau, tau_hat, varsigma, xi, eta_hat, eps));
    return rcpp_result_gen;
END_RCPP
}
// gevUpdateM
arma::colvec gevUpdateM(arma::colvec Y, arma::mat X, arma::colvec M, double alpha, double lambda, arma::mat D, arma::colvec beta0, arma::mat Omega0);
RcppExport SEXP _SpatGEVBMA_gevUpdateM(SEXP YSEXP, SEXP XSEXP, SEXP MSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP DSEXP, SEXP beta0SEXP, SEXP Omega0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omega0(Omega0SEXP);
    rcpp_result_gen = Rcpp::wrap(gevUpdateM(Y, X, M, alpha, lambda, D, beta0, Omega0));
    return rcpp_result_gen;
END_RCPP
}
// A
IntegerMatrix A(int p);
RcppExport SEXP _SpatGEVBMA_A(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(A(p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpatGEVBMA_ldot", (DL_FUNC) &_SpatGEVBMA_ldot, 6},
    {"_SpatGEVBMA_j_double_prime_new", (DL_FUNC) &_SpatGEVBMA_j_double_prime_new, 6},
    {"_SpatGEVBMA_j_prime_new", (DL_FUNC) &_SpatGEVBMA_j_prime_new, 6},
    {"_SpatGEVBMA_gev_like_new", (DL_FUNC) &_SpatGEVBMA_gev_like_new, 4},
    {"_SpatGEVBMA_g_prime_new", (DL_FUNC) &_SpatGEVBMA_g_prime_new, 6},
    {"_SpatGEVBMA_g_double_prime_new", (DL_FUNC) &_SpatGEVBMA_g_double_prime_new, 6},
    {"_SpatGEVBMA_f_prime_new", (DL_FUNC) &_SpatGEVBMA_f_prime_new, 6},
    {"_SpatGEVBMA_f_double_prime_new", (DL_FUNC) &_SpatGEVBMA_f_double_prime_new, 6},
    {"_SpatGEVBMA_g_eta_prime_new", (DL_FUNC) &_SpatGEVBMA_g_eta_prime_new, 6},
    {"_SpatGEVBMA_g_eta_double_prime_new", (DL_FUNC) &_SpatGEVBMA_g_eta_double_prime_new, 6},
    {"_SpatGEVBMA_gevUpdateM", (DL_FUNC) &_SpatGEVBMA_gevUpdateM, 8},
    {"_SpatGEVBMA_A", (DL_FUNC) &_SpatGEVBMA_A, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpatGEVBMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
